const { generateQRModules } = require('../module/qr-code');

/**
 * Helper: flatten QR modules to a binary string for comparison.
 */
function toBinaryString(modules, size) {
    let s = '';
    for (let y = 0; y < size; y++) {
        for (let x = 0; x < size; x++) {
            s += modules[y][x] ? '1' : '0';
        }
    }
    return s;
}

// These reference strings were generated by running lean-qr (reference/lean-qr)
// with mode.ascii() and EC level L (minCorrectionLevel: 0, maxCorrectionLevel: 0).
const REFERENCE = {
    Hello: {
        size: 21,
        data: '111111100101101111111100000100111001000001101110101101101011101101110100101001011101101110100010101011101100000100000101000001111111101010101111111000000001101100000000111011111111011000100111000000110001000011001010110000100011111101111001010001000010111100101110101010000000000001001010100110111111101101011100111100000101111110110000101110101001011100011101110100110001100110101110101110100010101100000101000001010010111111101000101100011'
    },
    'http://192.168.1.50:18881/download-ca': {
        size: 29,
        data: '1111111010000111110010111111110000010100111101011101000001101110101100101011000010111011011101011101001100110101110110111010011010111100101011101100000101110000010110010000011111111010101010101010111111100000000001101010100000000000110011100010110101110001011110100110000000111000011101111100111010111000011100001000001011001011100101101010101000111101001000010110011000010001011011101011010011110111011011111101110011111100100101101011101100011010101111001101001111010111011011000101000001010101110010010011110101010100110010101101000001011010011110100000100110010100100110100011111110100101011101011111110010000000011101001111010001000111111110011111111011101011101100000101101010101101000100011011101010001101010111111001010111010011001111001000101101101110100100000110111001010111000001011001010011011100001111111110101101110101110000010'
    },
    Ver1: {
        size: 21,
        data: '111111101111101111111100000101101101000001101110100111001011101101110100101101011101101110101000101011101100000101010001000001111111101010101111111000000001111000000000111001101111111110011001110000100000001001001100111000001000101000010000100100011001111110110000001000001000000001111011100010111111100101110111001100000101111011100000101110100111111110001101110100010000000000101110101000001000111100000101100100010000111111101010001001101'
    }
};

describe('QR Code Generator (lean-qr port)', () => {
    describe('generateQRModules basic properties', () => {
        it('should produce a square module matrix', () => {
            const { modules, size } = generateQRModules('test');
            expect(modules.length).toBe(size);
            modules.forEach((row) => expect(row.length).toBe(size));
        });

        it('should produce version-1 size (21x21) for short text', () => {
            const { size, version } = generateQRModules('Hi');
            expect(version).toBe(1);
            expect(size).toBe(21);
        });

        it('should only contain 0s and 1s', () => {
            const { modules } = generateQRModules('http://192.168.1.1:18881/download-ca');
            for (const row of modules) {
                for (const cell of row) {
                    expect(cell === 0 || cell === 1).toBe(true);
                }
            }
        });

        it('should produce deterministic output', () => {
            const r1 = generateQRModules('hello world');
            const r2 = generateQRModules('hello world');
            expect(r1.modules).toEqual(r2.modules);
        });

        it('should produce different output for different input', () => {
            const r1 = generateQRModules('aaa');
            const r2 = generateQRModules('bbb');
            expect(toBinaryString(r1.modules, r1.size)).not.toBe(toBinaryString(r2.modules, r2.size));
        });

        it('size should equal version * 4 + 17', () => {
            const { size, version } = generateQRModules('http://192.168.1.100:18881/download-ca');
            expect(size).toBe(version * 4 + 17);
        });
    });

    describe('finder patterns', () => {
        it('should have correct top-left finder pattern', () => {
            const { modules } = generateQRModules('test');
            // Row 0: all 7 dark
            for (let c = 0; c < 7; c++) expect(modules[0][c]).toBe(1);
            // Row 1: dark, 5 light, dark
            expect(modules[1][0]).toBe(1);
            for (let c = 1; c < 6; c++) expect(modules[1][c]).toBe(0);
            expect(modules[1][6]).toBe(1);
        });

        it('should have correct top-right finder pattern', () => {
            const { modules, size } = generateQRModules('test');
            for (let c = size - 7; c < size; c++) expect(modules[0][c]).toBe(1);
            expect(modules[1][size - 7]).toBe(1);
            for (let c = size - 6; c < size - 1; c++) expect(modules[1][c]).toBe(0);
            expect(modules[1][size - 1]).toBe(1);
        });

        it('should have correct bottom-left finder pattern', () => {
            const { modules, size } = generateQRModules('test');
            for (let c = 0; c < 7; c++) expect(modules[size - 1][c]).toBe(1);
            expect(modules[size - 2][0]).toBe(1);
            for (let c = 1; c < 6; c++) expect(modules[size - 2][c]).toBe(0);
            expect(modules[size - 2][6]).toBe(1);
        });
    });

    describe('exact match with lean-qr reference output', () => {
        for (const [text, expected] of Object.entries(REFERENCE)) {
            it(`should match reference for "${text.length > 20 ? text.slice(0, 20) + '...' : text}"`, () => {
                const { modules, size } = generateQRModules(text);
                expect(size).toBe(expected.size);
                const actual = toBinaryString(modules, size);
                expect(actual).toBe(expected.data);
            });
        }
    });
});
